# Generated by Django 6.0.4 on 2026-05-20 03:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار الموافقة'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='contracts.contract')),
                ('proposed_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='contracts.contractversion')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requested_contract_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_modification_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
