# Generated by Django 6.0.5 on 2026-05-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('SERVICES', 'عقد خدمات'), ('SUPPLY', 'عقد توريد'), ('RENT', 'عقد إيجار'), ('PARTNERSHIP', 'عقد شراكة'), ('CONSULTING', 'عقد استشاري'), ('EMPLOYMENT', 'عقد عمل'), ('OTHER', 'أخرى')], default='', max_length=20),
        ),
    ]
