# Generated by Django 6.0.4 on 2026-05-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_add_contract_type'),
        ('contracts', '0002_contractmodificationrequest'),
    ]

    operations = [
    ]
