# Generated by Django 6.0.4 on 2026-05-20 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_merge_20260520_1118'),
        ('invitations', '0003_signinginvitation_invitee_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInvitedParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('party_type', models.CharField(default='INDIVIDUAL', max_length=30)),
                ('signing_role', models.CharField(default='SIGNER', max_length=30)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('address_country', models.CharField(blank=True, max_length=100)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('commercial_registration', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('can_view_contract', models.BooleanField(default=True)),
                ('can_comment', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_upload_files', models.BooleanField(default=False)),
                ('can_sign', models.BooleanField(default=True)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('invitation_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_parties', to='contracts.contract')),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_invited_party', to='invitations.signinginvitation')),
            ],
            options={
                'db_table': 'contract_invited_parties',
                'unique_together': {('contract', 'email')},
            },
        ),
    ]
