# Generated by Django 6.0.4 on 2026-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractinvitedparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodificationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار الإرسال'), ('SENT', 'تم الإرسال'), ('VIEWED', 'تمت المشاهدة'), ('SIGNED', 'تم التوقيع'), ('EXPIRED', 'منتهي'), ('CANCELLED', 'ملغي'), ('FAILED', 'فشل الإرسال'), ('REJECTED', 'مرفوض'), ('ACCEPTED', 'تم القبول'), ('SUPERSEDED', 'تم استبدالها')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
