# Generated by Django 6.0.4 on 2026-05-16 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_full_name', models.CharField(max_length=255)),
                ('signer_mobile', models.CharField(max_length=15)),
                ('signer_email', models.EmailField(blank=True, max_length=254)),
                ('reference_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('secret_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار الإرسال'), ('SENT', 'تم الإرسال'), ('VIEWED', 'تمت المشاهدة'), ('SIGNED', 'تم التوقيع'), ('EXPIRED', 'منتهي'), ('CANCELLED', 'ملغي'), ('FAILED', 'فشل الإرسال')], db_index=True, default='PENDING', max_length=20)),
                ('sms_message', models.TextField(blank=True)),
                ('sms_provider', models.CharField(blank=True, max_length=50)),
                ('sms_provider_message_id', models.CharField(blank=True, max_length=255)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_invitations', to='contracts.contract')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_signing_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signing_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'status'], name='signinv_contract_status_idx'), models.Index(fields=['signer_mobile'], name='signinv_mobile_idx'), models.Index(fields=['-created_at'], name='signinv_created_idx')],
                'unique_together': {('contract', 'signer_mobile')},
            },
        ),
    ]
