# Generated by Django 6.0.4 on 2026-05-16 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signinginvitation',
            options={'ordering': ['signing_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='can_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='can_sign',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='can_upload_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='can_view_contract',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='contract_role',
            field=models.CharField(choices=[('FIRST_PARTY', 'الطرف الأول'), ('SECOND_PARTY', 'الطرف الثاني'), ('WITNESS', 'شاهد')], default='SECOND_PARTY', max_length=30),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='invitation_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='party_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'فرد'), ('ORGANIZATION', 'منشأة')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='signer_national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='signer_nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='signing_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='signing_role',
            field=models.CharField(choices=[('SIGNER', 'موقّع'), ('REVIEWER', 'مراجع'), ('APPROVER', 'معتمد')], default='SIGNER', max_length=30),
        ),
        migrations.AddField(
            model_name='signinginvitation',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signinginvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار الإرسال'), ('SENT', 'تم الإرسال'), ('VIEWED', 'تمت المشاهدة'), ('SIGNED', 'تم التوقيع'), ('EXPIRED', 'منتهي'), ('CANCELLED', 'ملغي'), ('FAILED', 'فشل الإرسال'), ('REJECTED', 'مرفوض')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='signinginvitation',
            index=models.Index(fields=['reference_number'], name='signinv_ref_idx'),
        ),
    ]
