# Generated by Django 6.0.4 on 2026-05-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_signinginvitation_invitee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinginvitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signinginvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار الإرسال'), ('SENT', 'تم الإرسال'), ('VIEWED', 'تمت المشاهدة'), ('SIGNED', 'تم التوقيع'), ('EXPIRED', 'منتهي'), ('CANCELLED', 'ملغي'), ('FAILED', 'فشل الإرسال'), ('REJECTED', 'مرفوض'), ('ACCEPTED', 'تم القبول')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
