# Generated by Django 6.0.5 on 2026-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('contract_created', 'تم إنشاء العقد وإرسال الدعوات'), ('contract_received', 'لديك عقد جديد للمراجعة'), ('contract_accepted', 'تم قبول العقد من الطرف الآخر'), ('contract_rejected', 'تم رفض العقد من الطرف الآخر'), ('contract_signed', 'تم التوقيع على العقد'), ('contract_completed', 'تم توثيق العقد على البلوكشين'), ('invitation_received', 'لديك دعوة توقيع جديدة'), ('invitation_expired', 'انتهت صلاحية دعوة التوقيع'), ('contract_modified', 'تم اقتراح تعديل على العقد'), ('subscription_expiring', 'اشتراكك سينتهي خلال 3 أيام'), ('subscription_expired', 'انتهت صلاحية اشتراكك'), ('contract_limit_reached', 'لقد وصلت إلى الحد الأقصى من العقود')], max_length=50),
        ),
    ]
